checkbox
daniilminin1990/flashCards04272024 pull request #105
Opened 2024-05-17 01:11 UTC by KirillDolzhenkov

2024-05-17 07:37 UTC, daniilminin1990 commented on src/components/ui/checkbox/checkbox.tsx
> +  const { checked, className, disabled, id, label, onCheckedChange, ...rest } = props
Зачем этот classname? В коде ниже его не к кому применять

2024-05-17 07:38 UTC, daniilminin1990 reviewed
className зачем?

2024-05-17 18:34 UTC, SiarheiHaurylchyk requested changes

2024-05-17 18:34 UTC, SiarheiHaurylchyk commented on src/components/ui/checkbox/checkbox.tsx
> +const Checkbox = forwardRef<ElementRef<typeof CheckboxRadix.Root>, Props>((props: Props) => {
Checkbox обернут forwardRef нужен ли он? Он не куда не повешен как я понимаю ... зачем он? Вероятно он нужен на {<CheckIcon />} ? Или вообще его убрать так как он не используется....

2024-05-17 18:34 UTC, SiarheiHaurylchyk commented on src/components/ui/checkbox/checkbox.tsx
> +                className={`CheckboxIndicator ${disabledClass} ${checkedClass}`}
Почему не используешь clsx ?

2024-05-17 18:34 UTC, SiarheiHaurylchyk commented on src/components/ui/checkbox/checkbox.tsx
>  import './checkbox.scss'
Используй module, переделать нужно

2024-05-17 18:34 UTC, SiarheiHaurylchyk commented on src/components/ui/checkbox/checkbox.tsx
> +      <form>
Нужна здесь форма без submit, если здесь будет работать без нее , убрать нужно!

2024-05-22 08:40 UTC, daniilminin1990 approved these changes

2024-05-22 08:59 UTC, merged